language: android
sudo: true
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra-android-m2repository
  - extra-android-support
  - junit-4.12
  - okhttp-2.7.5
  - okio-1.11.0
  - gson-2.8.0
  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script:
- "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_55dde564f0bc_key -iv $encrypted_55dde564f0bc_iv
  -in fayduan.jks.enc -out fayduan.jks -d
- rvm install 2.4.0
- gem install fir-cli
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: ZP18LN+hC9SOegQQMDOp+JMNr0W60T3rf8HH6qjqS9hzkHut3XGVwj5xptc3awYMsFSnkiW5zqSICtSNWmRvab4JHrjy2XVWVcZA4dNdPsiwg1yx7ISrq0ASgGgx6km6yoPnmV4xfRmo/M8C1ZNcFyFXBvoS/8aPSWp09FOGr9rZwYpKNSRdUyFfx1/fN4JlAxmg3ZEcjjYFh/i4w3ITKQEZTakI9+aQvl9yeBIX8DFukiVKMp8uF2mnWJAuLqu2MSt13uYBLD2qTjEWGoxUH5VF/ewgu7L6BrnRLWt2oxxwAaQyTV6XC7EyufLME+TJd2C+SNPOlBj7YyRn7dcXwUko4NGiQq77KSMj4eCg6SmxCYh6JONaJUps2WF2jKbnV1LCBKHiDU8+qfWXz+x+VypwLF9zggK1ZipWk9WthBZxVQ9NfjIc+rJJdcu933V0gceMPnvRwsBjrW4lMOZhYTxI4aRa1Cqpvg73eyevfVsHfQxr3C5Lm4Uwmz49lA49JiDe15wgz6GOgk24lTRZYbU6EtkJFNS2h8GiiLOUvNVnvo+2ADLD6z86tOM5/SjFhyVdqTQE6YNq97yMK82HFrg/3TBH1OL1EYt0v2WK4KTLaw/lwcuv2aHo8PlA2M2w/IJrGFNEseC738QIV2v1MNGtAgU4H5xLIZG5ORyuzhM=
  file_glob: true
  file: app/build/outputs/apk/Memory*.apk
  on:
    tags: true
    repo: fayduan/memory
after_deploy:
  - fir p app/build/outputs/apk/Memory*.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"
