package cn.duanyufei.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.duanyufei.model.Memory;
import cn.duanyufei.model.Motion;
import cn.duanyufei.model.Record;

import cn.duanyufei.greendao.MemoryDao;
import cn.duanyufei.greendao.MotionDao;
import cn.duanyufei.greendao.RecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig memoryDaoConfig;
    private final DaoConfig motionDaoConfig;
    private final DaoConfig recordDaoConfig;

    private final MemoryDao memoryDao;
    private final MotionDao motionDao;
    private final RecordDao recordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        memoryDaoConfig = daoConfigMap.get(MemoryDao.class).clone();
        memoryDaoConfig.initIdentityScope(type);

        motionDaoConfig = daoConfigMap.get(MotionDao.class).clone();
        motionDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        memoryDao = new MemoryDao(memoryDaoConfig, this);
        motionDao = new MotionDao(motionDaoConfig, this);
        recordDao = new RecordDao(recordDaoConfig, this);

        registerDao(Memory.class, memoryDao);
        registerDao(Motion.class, motionDao);
        registerDao(Record.class, recordDao);
    }
    
    public void clear() {
        memoryDaoConfig.clearIdentityScope();
        motionDaoConfig.clearIdentityScope();
        recordDaoConfig.clearIdentityScope();
    }

    public MemoryDao getMemoryDao() {
        return memoryDao;
    }

    public MotionDao getMotionDao() {
        return motionDao;
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

}
